### ISSUE TITLE
Find HSC Zero Points 

### ISSUE THREAD

**Issue by robelgeda** [robelgeda/dsii_dwarfs#6]
Numbers that convert from Mag to counts per second in the image.

**Comment by hcferguson** [comment]
The header of the file we downloaded `calexp-HSC-G-17130-3,0.fits` has a keyword 

`FLUXMAG0=     63095734448.0194`

This value gives  2.5*log(FLUXMAG0) = 27.0, so I suspect these images are scaled so that this is always the case. And I would guess that this is AB magnitude for a flat-spectrum source in the bandpass. So that's what we need to try to confirm by looking at the documentation. Having this keyword to search on might be a clue.

**Comment by robelgeda** [comment]
### Note
`T_MAGZER F6.3  double    mag/sec/ADU Magnitude zero point (ZP)`
https://www.naoj.org/Observing/Instruments/HSC/HSC_FITSdic.dat

**Comment by robelgeda** [comment]
`m_obs = -2.5 * { log10( Flux valu in catalog ) - log10( FLUXMAG0 ) }`

> HSC pipeline uses the following value to all filters;
> FLUXMAG0 = 63095734448.0194 ~ 27 mag

<img width="1256" alt="Screen Shot 2019-06-28 at 12 14 32 PM" src="https://user-images.githubusercontent.com/10345916/60356206-66cb6900-999e-11e9-9532-902ea2321637.png">


https://hsc.mtk.nao.ac.jp/pipedoc_e/e_usage/multiband.html

**Comment by hcferguson** [comment]
This looks good!
